package com.hepexta.jaxrs.bank.repository.db;

public interface Queries {
    String QUERY_CBS_ACCOUNT_FIND_BY_ID = "SELECT * FROM CBS_ACCOUNT ACC LEFT JOIN CBS_CLIENT CL ON ACC.CLIENTID = CL.CLIENTID WHERE ACCOUNTID = ?";
    String QUERY_CBS_ACCOUNT_FIND_BY_ID_AND_LOCK = "SELECT * FROM CBS_ACCOUNT WHERE ACCOUNTID = ? FOR UPDATE";
    String QUERY_CBS_ACCOUNT_GET_LIST = "SELECT * FROM CBS_ACCOUNT ACC LEFT JOIN CBS_CLIENT CL ON ACC.CLIENTID = CL.CLIENTID";
    String QUERY_CBS_ACCOUNT_INSERT = "INSERT INTO CBS_ACCOUNT (NUMBER, CLIENTID, BALANCE) VALUES (?, ?, ?)";
    String QUERY_CBS_ACCOUNT_UPDATE = "UPDATE CBS_ACCOUNT SET NUMBER = ?, CLIENTID = ?, BALANCE = ? WHERE ACCOUNTID = ?";
    String QUERY_CBS_ACCOUNT_DELETE = "DELETE FROM CBS_ACCOUNT WHERE ACCOUNTID = ?";

    String QUERY_CBS_CLIENT_GET_LIST = "SELECT * FROM CBS_CLIENT";
    String QUERY_CBS_CLIENT_FIND_BY_ID = "SELECT * FROM CBS_CLIENT WHERE CLIENTID = ?";
    String QUERY_CBS_CLIENT_INSERT = "INSERT INTO CBS_CLIENT (NAME) VALUES (?)";
    String QUERY_CBS_CLIENT_DELETE = "DELETE FROM CBS_CLIENT WHERE CLIENTID = ?";
    String QUERY_CBS_CLIENT_UPDATE = "UPDATE CBS_CLIENT SET NAME = ? WHERE CLIENTID = ?";

    String QUERY_CBS_TRANSACTION_INSERT = "INSERT INTO CBS_TRANSACTION (SRCACCOUNTID, DSTACCOUNTID, OPERDATE, AMOUNT, COMMENT, STATUS, MESSAGE) VALUES (?, ?, ?, ?, ?, ?, ?)";
    String QUERY_CBS_TRANSACTION_UPDATE_STATUS = "UPDATE CBS_TRANSACTION SET STATUS = ?, MESSAGE = ? WHERE TRANSACTIONID = ?";
    String QUERY_CBS_TRANSACTION_FIND_BY_ACCOUNT_ID = "SELECT * FROM CBS_TRANSACTION WHERE SRCACCOUNTID = ? OR DSTACCOUNTID = ?";
}
