DROP TABLE IF EXISTS CBS_CLIENT;

CREATE TABLE CBS_CLIENT (
  CLIENTID VARCHAR(30) PRIMARY KEY AUTO_INCREMENT NOT NULL,
  NAME VARCHAR(30) NOT NULL
);

INSERT INTO CBS_CLIENT (NAME) VALUES ('John Smith');
INSERT INTO CBS_CLIENT (NAME) VALUES ('Peter Parker');
INSERT INTO CBS_CLIENT (NAME) VALUES ('Keanu Reeves');

DROP TABLE IF EXISTS CBS_ACCOUNT;

CREATE TABLE CBS_ACCOUNT (
  ACCOUNTID VARCHAR(30) PRIMARY KEY AUTO_INCREMENT NOT NULL,
  NUMBER VARCHAR(30),
  CLIENTID VARCHAR(30),
  BALANCE DECIMAL(19,4)
);

CREATE INDEX IDX_ACCOUNT_CLIENTID on CBS_ACCOUNT(CLIENTID);

INSERT INTO CBS_ACCOUNT (NUMBER, CLIENTID, BALANCE) VALUES ('ACC01', '1', 100.0000);
INSERT INTO CBS_ACCOUNT (NUMBER, CLIENTID, BALANCE) VALUES ('ACC01', '2', 200.0000);
INSERT INTO CBS_ACCOUNT (NUMBER, CLIENTID, BALANCE) VALUES ('ACC01', '3', 300.0000);

DROP TABLE IF EXISTS CBS_TRANSACTION;

CREATE TABLE CBS_TRANSACTION (
  TRANSACTIONID VARCHAR(30) PRIMARY KEY AUTO_INCREMENT NOT NULL,
  SRCACCOUNTID VARCHAR(30) NOT NULL,
  DSTACCOUNTID VARCHAR(30) NOT NULL,
  TRANSTYPE INTEGER,
  OPERDATE DATE,
  AMOUNT DECIMAL(19,4),
  COMMENT VARCHAR(300)
);

INSERT INTO CBS_TRANSACTION (SRCACCOUNTID, DSTACCOUNTID, TRANSTYPE, OPERDATE, AMOUNT, COMMENT)
VALUES ('1', '2', '1', '2019-7-04', 100.0000, 'Transfer from John to Peter');
INSERT INTO CBS_TRANSACTION (SRCACCOUNTID, DSTACCOUNTID, TRANSTYPE, OPERDATE, AMOUNT, COMMENT)
VALUES ('2', '3', '1', '2019-7-04', 100.0000, 'Transfer from Peter to Keanu');
INSERT INTO CBS_TRANSACTION (SRCACCOUNTID, DSTACCOUNTID, TRANSTYPE, OPERDATE, AMOUNT, COMMENT)
VALUES ('3', null, '1', '2019-7-04', 100.0000, 'Withdrawal');
