INSERT INTO CBS_CLIENT (NAME) VALUES ('Bank');
INSERT INTO CBS_CLIENT (NAME) VALUES ('John Smith');
INSERT INTO CBS_CLIENT (NAME) VALUES ('Peter Parker');
INSERT INTO CBS_CLIENT (NAME) VALUES ('Keanu Reeves');

INSERT INTO CBS_ACCOUNT (NUMBER, CLIENTID, BALANCE) VALUES ('CASH ACCOUNT', '1', 10000.0000);
INSERT INTO CBS_ACCOUNT (NUMBER, CLIENTID, BALANCE) VALUES ('EXPENSES', '1', 10000.0000);
INSERT INTO CBS_ACCOUNT (NUMBER, CLIENTID, BALANCE) VALUES ('ACC02', '2', 100.0000);
INSERT INTO CBS_ACCOUNT (NUMBER, CLIENTID, BALANCE) VALUES ('ACC03', '3', 100.0000);
INSERT INTO CBS_ACCOUNT (NUMBER, CLIENTID, BALANCE) VALUES ('ACC04', '4', 200.0000);

INSERT INTO CBS_TRANSACTION (SRCACCOUNTID, DSTACCOUNTID, OPERDATE, AMOUNT, COMMENT)
VALUES ('3', '4', '2019-9-04', 100.0000, 'Transfer from John to Peter');
INSERT INTO CBS_TRANSACTION (SRCACCOUNTID, DSTACCOUNTID, OPERDATE, AMOUNT, COMMENT)
VALUES ('4', '5', '2019-9-04', 100.0000, 'Transfer from Peter to Keanu');
INSERT INTO CBS_TRANSACTION (SRCACCOUNTID, DSTACCOUNTID, OPERDATE, AMOUNT, COMMENT)
VALUES ('3', '2','2019-9-04', 100.0000, 'Withdrawal');
