DROP TABLE IF EXISTS CBS_CLIENT;

CREATE TABLE CBS_CLIENT (
  CLIENTID VARCHAR(30) PRIMARY KEY AUTO_INCREMENT NOT NULL,
  NAME VARCHAR(30) NOT NULL
);

DROP TABLE IF EXISTS CBS_ACCOUNT;

CREATE TABLE CBS_ACCOUNT (
  ACCOUNTID VARCHAR(30) PRIMARY KEY AUTO_INCREMENT NOT NULL,
  NUMBER VARCHAR(30),
  CLIENTID VARCHAR(30),
  BALANCE DECIMAL(19,4)
);

CREATE INDEX IDX_ACCOUNT_CLIENTID on CBS_ACCOUNT(CLIENTID);

DROP TABLE IF EXISTS CBS_TRANSACTION;

CREATE TABLE CBS_TRANSACTION (
  TRANSACTIONID VARCHAR(30) PRIMARY KEY AUTO_INCREMENT NOT NULL,
  SRCACCOUNTID VARCHAR(30) NOT NULL,
  DSTACCOUNTID VARCHAR(30) NOT NULL,
  TRANSTYPE INTEGER,
  OPERDATE DATE,
  AMOUNT DECIMAL(19,4),
  COMMENT VARCHAR(300),
  STATUS VARCHAR(10),
  MESSAGE VARCHAR(300)
);
