DROP TABLE IF EXISTS CBS_CLIENT;

CREATE TABLE CBS_CLIENT (
  CLIENTID VARCHAR(30) PRIMARY KEY AUTO_INCREMENT NOT NULL,
  NAME VARCHAR(30) NOT NULL
);

INSERT INTO CBS_CLIENT (NAME) VALUES ('Bank');
INSERT INTO CBS_CLIENT (NAME) VALUES ('John Smith');
INSERT INTO CBS_CLIENT (NAME) VALUES ('Peter Parker');
INSERT INTO CBS_CLIENT (NAME) VALUES ('Keanu Reeves');

DROP TABLE IF EXISTS CBS_ACCOUNT;

CREATE TABLE CBS_ACCOUNT (
  ACCOUNTID VARCHAR(30) PRIMARY KEY AUTO_INCREMENT NOT NULL,
  NUMBER VARCHAR(30),
  CLIENTID VARCHAR(30),
  BALANCE DECIMAL(19,4)
);

CREATE INDEX IDX_ACCOUNT_CLIENTID on CBS_ACCOUNT(CLIENTID);

INSERT INTO CBS_ACCOUNT (NUMBER, CLIENTID, BALANCE) VALUES ('CASH ACCOUNT', '1', 100.0000);
INSERT INTO CBS_ACCOUNT (NUMBER, CLIENTID, BALANCE) VALUES ('EXPENSES', '1', 10000.0000);
INSERT INTO CBS_ACCOUNT (NUMBER, CLIENTID, BALANCE) VALUES ('ACC02', '2', 100.0000);
INSERT INTO CBS_ACCOUNT (NUMBER, CLIENTID, BALANCE) VALUES ('ACC03', '3', 100.0000);
INSERT INTO CBS_ACCOUNT (NUMBER, CLIENTID, BALANCE) VALUES ('ACC04', '4', 200.0000);

DROP TABLE IF EXISTS CBS_TRANSACTION;

CREATE TABLE CBS_TRANSACTION (
  TRANSACTIONID VARCHAR(30) PRIMARY KEY AUTO_INCREMENT NOT NULL,
  SRCACCOUNTID VARCHAR(30) NOT NULL,
  DSTACCOUNTID VARCHAR(30) NOT NULL,
  TRANSTYPE INTEGER,
  OPERDATE DATE,
  AMOUNT DECIMAL(19,4),
  COMMENT VARCHAR(300)
);

INSERT INTO CBS_TRANSACTION (SRCACCOUNTID, DSTACCOUNTID, OPERDATE, AMOUNT, COMMENT)
VALUES ('3', '4', '2019-9-04', 100.0000, 'Transfer from John to Peter');
INSERT INTO CBS_TRANSACTION (SRCACCOUNTID, DSTACCOUNTID, OPERDATE, AMOUNT, COMMENT)
VALUES ('4', '5', '2019-9-04', 100.0000, 'Transfer from Peter to Keanu');
INSERT INTO CBS_TRANSACTION (SRCACCOUNTID, DSTACCOUNTID, OPERDATE, AMOUNT, COMMENT)
VALUES ('3', '2','2019-9-04', 100.0000, 'Withdrawal');
